---
name: filelight
version: 17.08.1
summary: View disk usage information
description: |-
    Filelight allows you to understand your disk usage by graphically representing your filesystem as a set of concentric, segmented rings.

    It is like a pie-chart, but the segments nest, allowing you to see both which directories take up all your space, and which directories and files inside those directories are the real culprits.
confinement: strict
grade: stable
apps:
    filelight:
        command: kf5-launch filelight
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.filelight
        bus: session
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-all
        interface: content
        default-provider: kde-frameworks-5
        target: kf5
parts:
    filelight:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - kdoctools-dev
        - libpulse0
        source: https://download.kde.org/stable/applications/17.08.1/src/filelight-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
